### ISSUE TITLE
[Witch] (Will) Spells are all available for casting, but witches should prepare and cast like wizards

### ISSUE THREAD

**Issue by yuri-ccp** [InstantMirage/PathfinderBG3Mod#31]
[Witch] (Will) Spells are all available for casting, but witches should prepare and cast like wizards.

**Comment by InstantMirage** [comment]
It doesn't have you prepare them at all? I have a theory on why but I'm surprised it hasn't been brought up before

**Comment by yuri-ccp** [comment]
No I'm even unable to (de)select what to prepare it just shows all learned spells are simply castable by default.

![Image](https://github.com/user-attachments/assets/af27eb53-49ee-492f-98cf-03fc37dd245d)

**Comment by InstantMirage** [comment]
should be fixed now

**Comment by yuri-ccp** [comment]
The problem continues. I tried to respec Will but didn't solve the problem. I also tried to load before take Will, but also it was unsuccessful. I also disable all other mode beyond PF2e (and +10 critical hit/d20 initiative) but the issue persists.

So then I created a new character with Witch class and the issue persists. Unfortunately, the last fix doesn't work.

![Image](https://github.com/user-attachments/assets/41227a02-6670-4d0f-abf1-1cf59290f472)

**Comment by yuri-ccp** [comment]
It's now working almost fine. Thanks!

The problem now is that for some reason, my level 3 Will can prepare 7 spells. Flexible spellcasting should be 4 spell (collection) in this level or if it will use the main rule it should be the same number of available spellslots.

**Comment by InstantMirage** [comment]
That is hardcoded. We can't change # of prepared spells
